# Note: You can use any Debian/Ubuntu based image you want. 
FROM debian:10

# Install needed packages and setup non-root user. Use a separate RUN statement to add your own dependencies.
ARG USERNAME=root
ARG ENABLE_NONROOT_DOCKER="true"
ARG SOURCE_SOCKET=/var/run/docker-host.sock
ARG TARGET_SOCKET=/var/run/docker.sock
COPY library-scripts/*.sh /tmp/library-scripts/
RUN apt-get update && DEBIAN_FRONTEND=noninteractive \
    && bash /tmp/library-scripts/desktop-lite-debian.sh "${USERNAME}" "vscode" "true" \
#    && bash /tmp/library-scripts/docker-debian.sh "${ENABLE_NONROOT_DOCKER}" "${SOURCE_SOCKET}" "${TARGET_SOCKET}" "${USERNAME}" \
#    && bash /tmp/library-scripts/sshd-debian.sh "2222" "${USERNAME}" "false" "skip" \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/library-scripts/

ENV DBUS_SESSION_BUS_ADDRESS="autolaunch:" \
    DISPLAY=":1" \
    LANG="en_US.UTF-8" \
	LANGUAGE="en_US.UTF-8"

# Setting the ENTRYPOINT to docker-init.sh will configure non-root access to 
# the Docker socket if "overrideCommand": false is set in devcontainer.json. 
# The script will also execute CMD if you need to alter startup behaviors.
#ENTRYPOINT [ "/usr/local/share/docker-init.sh", "/usr/local/share/ssh-init.sh", "/usr/local/share/desktop-init.sh" ]
ENTRYPOINT [ "/usr/local/share/desktop-init.sh" ]
CMD [ "sleep", "infinity" ]

# Install Chrome
#RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#    && curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o /tmp/chrome.deb \
#    && apt-get -y install /tmp/chrome.deb \
#    && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/chrome.deb

# Install VS Code Insiders
#RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#    && curl -sSL https://go.microsoft.com/fwlink/?LinkID=760865 -o /tmp/code-insiders.deb \
#    && apt-get -y install /tmp/code-insiders.deb \
#    && update-alternatives --set editor /usr/bin/code* \
#    && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/code-insiders.deb

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
